# Generated by Django 4.1 on 2023-01-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel("Skills", "Skill")
    ]
