# Generated by Django 4.1 on 2023-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default=100, max_length=3),
            preserve_default=False,
        ),
    ]
